branch-defaults:
  default:
    environment: node-express-env
    group_suffix: null
  main:
    environment: node-express-env
environment-defaults:
  node-express-env:
    branch: null
    repository: null
global:
  application_name: eb-express
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
